# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e15249a1f827e1f2b13bae63b638000888d3773b1432f0af71c7bd46f3a82a4b4d16c117fe18c0a6cb19c8dd481ecba14e09e134d44471a2e62204220586403

test:
  secret_key_base: 554b6e4877a6df075068ea4c898ea291075b0536f2f1cc340299cf49e544a7e05f00d27dcd58454a216887d0aa0b4cb61b73ddd24c8f3c669908701d7248927b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
